menu:
  首页: /
  归档: /archives
rss: /atom.xml

archive_date_format: MMM DD
fancybox: true

language: zh-CN

duoshuo_shortname: riverisme

baidu_analytics: 4fba5193867e858e3f8e05b049feb134

favicon: /favicon.ico
